---
title: "Data import"
author: "Bingyu Sun"
date: "9/18/2018"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Import FAS csv files

Import my first csv.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```
use janitor package clean_name function

Import my second csv.

```{r}
FAS_pups_data = read_csv(file = "./data/FAS_pups.csv")
```

## Look at data

Look at litters data.

```{r}
head(litters_data)
tail(litters_data)

skimr::skim(litters_data)
```

Skip some rows; omit variable name

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

Look at FAS pups data

```{r}
pups_data = read_csv("./data/FAS_pups.csv")
pups_data = 
```

## Other formats

Read in mlb data

```{r}
mlb_data = readxl::read_excel(path = "./data/mlb11.xlsx")

mlb_subset = readxl::read_excel(path = "./data/mlb11.xlsx", range = "A1:E17")
```

Read in pulse data:

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
```


## Compare with base R

```{r}
pups_readr = read_csv("./data/FAS_pups.csv")
pups_baser = read.csv("./data/FAS_pups.csv")

pups_readr
pups_baser
```
read.csv gives more data and can guess
