---
title: "Tidy data"
author: "Bingyu Sun"
date: "9/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## gather

PULSE data

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data
```

This isn't tidy yet...

```{r}
pulse_tidy = pulse_data %>%
  gather(key = visit, value = bdi, bdi_score_bl:bdi_score_12m)
```

Illustrate 'separate':

```{r}
pulse_tidy %>%
  separate(visit, into = c("bdi_str", ))
```

Practice 1

```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>% 
  janitor::clean_names() %>%
  select(litter_number, ends_with("weight")) %>%
  gather(key = "gest_day", value = "weight", gd0_weight:gd18_weight) %>%
  mutate(gest_day = recode(gest_day, "gd0_weight" = 0, "gd18_weight" = 18)) %>%
  arrange(litter_number)
```

## Spread

knitr::kable() make it nice in report

## Data

```{r}
fellowship_ring = readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")
```
Not a good way, write a function to make it quick and easier process

Create finla LotR data:

```{r}
bind_rows(fellowship_ring, two_towers, return_king) %>%
  janitor::clean_names() %>%
  gather(key = sex, value = word, female:male) %>%
  mutate(race = tolower(race))
```

## Join data

Load the FAS dataset

